VERBOSE = False
CIRCULAR_VIRUS = True

HOST_SEG_LP_COE = None
VIRUS_SEG_LP_COE = None
JUNCTION_LP_COE = None
INFER_COV_COE = None
INFERRED_JUNCTION_WEIGHT = None
SV_WEIGHT = None
INTEG_WEIGHT = None

EDGE_SELECTION = 'smart_random'
DELETE_INCOMPATIBLE_EDGES = False

MAX_BRUTE_FORCE_LOOPS = 10000
CHOOSE_SIMPLE_CONTIG = False
LIMIT_SIMPLE_CONTIG = -1

OUTPUT_LP = None

#
INFER_NORMAL_JUNCTIONS = True
IF_DELETE_NORMAL_ALLELE = True
DELETE_NORMAL = {}
LP_WITH_ORIGINAL_PLOIDY = False
EQUALLY_ASSIGN_UCYC_TO_ALLELES = False

CAP_JUNCTION_WEIGHT = None
AUTO_WEIGHING = False
WEIGHT_BY_LENGTH = None
WEIGHT_BY_CN = None
# OVERRIDE_WEIGHT = False
PRINT_RESULT = False